version: "3"

services:
   b:
     build:
          dockerfile: Dockerfile
          context: .
     environment:
      VIRTUAL_HOST: b.localhost
     expose:
       - 80   
networks:
  default:
    external:
      name: nginx-proxy