a:
  build: a
  environment:
    VIRTUAL_HOST: a.serviya.co
  restart: always
  expose:
       - 80

b:
  build: b
  environment:
    VIRTUAL_HOST:  b.serviya.co
  restart: always
  expose:
       - 80
c:
  build: c
  environment:
    VIRTUAL_HOST: serviya.co
  restart: always  
  expose:
       - 80
      
nginx-proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  privileged: true
networks:
  default:
    external:
      name: nginx-proxy  
