a:
  build: a
  environment:
    VIRTUAL_HOST: a.localhost
  restart: always
  expose:
       - 80

b:
  build: b
  environment:
    VIRTUAL_HOST:  b.localhost
  restart: always
  expose:
       - 80
c:
  build: c
  environment:
    VIRTUAL_HOST: localhost
  restart: always  
  expose:
       - 80

nginx-proxy:
  image: jwilder/nginx-proxy
  environment:
    VIRTUAL_HOST: serviya.co
    VIRTUAL_PORT: 80
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  privileged: true
